POST http://localhost:3333/tenis
Content-Type: application/json

{
    "modelo": "Tenis",
    "marca": "Marca01",
    "pares": 1000
}

###

GET http://localhost:3333/tenis

###

GET http://localhost:3333/tenis?search=Jordan

###

PUT http://localhost:3333/tenis/013211c5-a086-4280-94a1-3f129f68a686
Content-Type: application/json

{
    "modelo": "Jordan",
    "marca": "Nike",
    "pares": 200
}

###

DELETE http://localhost:3333/tenis/013211c5-a086-4280-94a1-3f129f68a686