POST http://localhost:3333/localhost:3333/tenis
Content-Type: application/json

{
    "modelo": "jordan TENIS:",
    "marca": "nike:",
    "pares": 1000 

}

###NPM

GET http://localhost:3333/localhost:3333/tenis

###

GET http://localhost:3333/tenis?search=tenis

###

PUT http://localhost:3333/tenis/5aea1252-ee29-4cae-9bc3-04f330403d85
Content-Type: application/json 

{
    "modelo": "adi2000",
    "marca": "adidas",
    "pares": 200
}

###

DELETE http://localhost:3333/localhost:3333/tenis/5aea1252-ee29-4cae-9bc3-04f330403d85